### ISSUE TITLE
[solved] tig - command not found

### ISSUE THREAD

**Issue by RidaAyed** [rolfschr/GSWL-private#1]
In case anyone else stumbles on the same issue: 

I had to install https://github.com/jonas/tig in order to get this line working:

https://github.com/rolfschr/GSWL-private/blob/master/.tmuxinator.GSWL-private.yml#L27

**Comment by rolfschr** [comment]
Thanks, I added ``tig`` to the [list of optional deps](https://github.com/rolfschr/GSWL-book/commit/6c9ac98e956feb5ed9cd0bd5f8b5fc65ebdb7432).
